version: '3.9'

services:

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5432:5432"
        - "5433:5433"
        - "5434:5434"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      CORE_SETTINGS_DATABASES: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      CORE_SETTINGS_LOCAL_PATH: 'local/settings.py'
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local